proyecto-1/Models/proveedores.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proveedores()
        {
            this.proveedores_productos = new HashSet<proveedores_productos>();
            this.proveedores_comercios = new HashSet<proveedores_comercios>();
        }
    
        public int id_proveedor { get; set; }
        public string razon_social { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proveedores_productos> proveedores_productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<proveedores_comercios> proveedores_comercios { get; set; }
    }
}

proyecto-1/Controllers/ProveedoresController.cs
using proyecto_1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using proyecto_1.Models.ViewModel;

namespace proyecto_1.Controllers
{
    public class ProveedoresController : Controller
    {
        // GET: Proveedores
        public ActionResult Index()
        {
            try
            {
               
                int idComercio = 0;

                if (Session.Count > 1)
                {
                  //  idEmpleado = (int)Session["usuario"];
                    idComercio = (int)Session["comercio"];
                }
                
                List<ListaProveedoresViewModel> lst = null;
                using (practicaprofesionalEntities1 db = new practicaprofesionalEntities1())
                {
                    lst = (from p in db.proveedores
                           join pc in db.proveedores_comercios on
                           p.id_proveedor equals pc.id_proveedor
                           where pc.id_comercio == idComercio 
                           && p.estado == "1"
                           select new ListaProveedoresViewModel
                           {
                               id = p.id_proveedor,
                               razon_social = p.razon_social,
                               email = p.email,
                               telefono = p.telefono
                           }).ToList();
                }

                return View(lst);
            }
            catch (Exception e)
            {
                return Content("error no tiene permiso para entrar" + e.Message);
            }
        }


         [HttpGet]
        public ActionResult Crear()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Crear(ProveedorViewModel model)
        {

            int idComercio = (int)Session["comercio"];

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (practicaprofesionalEntities1 db = new practicaprofesionalEntities1())
            {
                proveedores oProveedor = new proveedores();

                oProveedor.razon_social = model.razon_social;
                oProveedor.estado = "1";
                oProveedor.email = model.email;
                oProveedor.telefono = Convert.ToString(model.telefono);
                
                db.proveedores.Add(oProveedor);

                db.SaveChanges();

                int newIdentityValue = oProveedor.id_proveedor;

                //insert en tabla proveedores_comercios
                proveedores_comercios p_comercio = new proveedores_comercios();
                p_comercio.id_comercio = idComercio;
                p_comercio.id_proveedor = newIdentityValue;

                db.proveedores_comercios.Add(p_comercio);
                db.SaveChanges();
                TempData["Referrer"] = "SaveRegister";



            }

            return Redirect(Url.Content("~/Proveedores"));
        }


        [HttpGet]
        public ActionResult Editar(int id)
        {
            int idComercio = (int)Session["comercio"];

            EditarProveedorViewModel model = new EditarProveedorViewModel();

            using (var db = new practicaprofesionalEntities1())
            {
                var oProveedor = db.proveedores.Find(id);
                model.razon_social = oProveedor.razon_social;
                model.email = oProveedor.email;
                model.telefono = Convert.ToInt32(oProveedor.telefono);
               
            }



            return View(model);
        }


        [HttpPost]
        public ActionResult Editar(EditarProveedorViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var db = new practicaprofesionalEntities1())
            {
                var oProveedor = db.proveedores.Find(model.id);
                oProveedor.razon_social = model.razon_social.Trim();
                oProveedor.email = model.email;
                oProveedor.telefono = Convert.ToString(model.telefono);


                db.Entry(oProveedor).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                TempData["Referrer"] = "SaveRegister";


            }

            return Redirect(Url.Content("~/Proveedores"));

        }

        [HttpPost]
        public ActionResult Eliminar(int id)
        {
            try
            {
                using (var db = new practicaprofesionalEntities1())
                {
                    var oPoveedor = db.proveedores.Find(id);
                    oPoveedor.estado = "0"; //eliminado logico

                    db.Entry(oPoveedor).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }

                return Content("1");
            }
            catch (Exception e)
            {
                return Content("ocurrio un problema al elminar el producto", e.Message);
            }
        }



    }
}

proyecto-1/Views/Proveedores/Crear.cshtml
@model proyecto_1.Models.ViewModel.ProveedorViewModel
@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>

<div class="row">
    <div class="col-md-12">

        @using (Html.BeginForm("Crear", "Proveedores", FormMethod.Post, new { role = "form", @class = "" }))
        {
            @Html.AntiForgeryToken() //arroja excepcion no controlada


            @Html.ValidationMessage("error", new { @class = "text-danger" })



            @Html.LabelFor(d => d.razon_social)
            <br />@Html.ValidationMessageFor(d => d.razon_social, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.razon_social, new { @class = "form-control" })


            @Html.LabelFor(d => d.email)
            <br />@Html.ValidationMessageFor(d => d.email, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.email, new { @class = "form-control" })


            @Html.LabelFor(d => d.telefono)
            <br />@Html.ValidationMessageFor(d => d.telefono, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.telefono, new { @class = "form-control" })


    <div style="text-align:center" class="boton">
        <input type="button" value="Volver" class="btn btn-primary" onclick="document.location.href= '@Url.Content("~/Proveedores/Index")'" />
        <input type="submit" class="btn btn-primary" value="Crear" />

    </div>

        }
    </div>

</div>

proyecto-1/Views/Proveedores/Editar.cshtml
@model proyecto_1.Models.ViewModel.EditarProveedorViewModel
@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

<div class="row">
    <div class="col-md-12">

        @using (Html.BeginForm("Editar", "Proveedores", FormMethod.Post, new { role = "form", @class = "" }))
        {
            @Html.AntiForgeryToken() //arroja excepcion no controlada


            @Html.ValidationMessage("error", new { @class = "text-danger" })



            @Html.LabelFor(d => d.razon_social)
            <br />@Html.ValidationMessageFor(d => d.razon_social, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.razon_social, new { @class = "form-control" })


            @Html.LabelFor(d => d.email)
            <br />@Html.ValidationMessageFor(d => d.email, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.email, new { @class = "form-control" })


            @Html.LabelFor(d => d.telefono)
            <br />@Html.ValidationMessageFor(d => d.telefono, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.telefono, new { @class = "form-control" })


    <div style="text-align:center" class="boton">
        <input type="button" value="Volver" class="btn btn-primary" onclick="document.location.href= '@Url.Content("~/Proveedores/Index")'" />
        <input type="submit" class="btn btn-primary" value="Editar" />

    </div>

        }
    </div>

</div>

proyecto-1/Views/Proveedores/Index.cshtml
@model List<proyecto_1.Models.ViewModel.ListaProveedoresViewModel>
@{
    ViewBag.Title = "Proveedores";
}

<h2>@ViewBag.Title</h2>
<div class="row">
    <div class="boton">
        <input type="submit" value="Agregar" class="btn btn-primary" onclick="document.location.href= '@Url.Content("~/Proveedores/Crear")'" />
    </div>
</div>

@if ((string)TempData["Referrer"] == "SaveRegister")
{
    <div class="alert alert-success">
        <strong>Su carga se realizo exitosamente</strong>
    </div>
}

<div class="row">
    <div class="col-lg-12">
        <table class="table" id="datatable">

            <thead>
                <tr>
                    <th>#</th>
                    <th>Razon Social</th>
                    <th>Email</th>
                    <th>Telefono</th>
                    <th>  </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var oProveedor in Model)
                {
                    <tr>
                        <td>@oProveedor.id </td>
                        <td>@oProveedor.razon_social </td>
                        <td>@oProveedor.email </td>
                        <td>@oProveedor.telefono</td>
                        <td>

                            @if (Session.Count > 1 && (int)Session["tipo"] == 1)
                            {
                                <input type="submit" value="Editar" class="btn btn-success" onclick="document.location.href='@Url.Content("~/Proveedores/Editar/" + oProveedor.id)'" />
                                <input type="submit" value="Eliminar" class="btn btn-danger" onclick="jsDelete(@oProveedor.id);" />
                            }
                        </td>

                    </tr>
                }
            </tbody>
        </table>

    </div>

</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $('#datatable').DataTable();
        });



    </script>
}

<script>
     function jsDelete(id) {
         if (confirm("esta seguro que desa confirmar?"))
         {
                url = "@Url.Content("~/Proveedores/Eliminar")" + "/" + id;

            $.post(url, function (data)
            {
                if (data == "1")
                {
                      document.location.href = "@Url.Content("~/Proveedores")"
                }
                else
                {
                        alert("ocurrio un problema al eliminar el Proveedor")
                }
            })
         }
     }
</script>