proyecto-1/Models/ViewModel/ComercioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace proyecto_1.Models.ViewModel
{
    public class ComercioViewModel
    {
        [Required]
        [StringLength(maximumLength:50,ErrorMessage ="La razon social debe tener como maximo {0} caracteres ")]
        [Display(Name = "Razon Social")]
        public string razon_social { get; set; }

        [Required]
        [Display(Name = "Situacion frente al IVA")]
        public int id_IVA { get; set; }
        public string descripcion { get; set; }


        [Required]
        [StringLength(maximumLength: 16, ErrorMessage = "Ingresos Brutos debe tener como maximo {0} caracteres ")]
        [Display(Name = "Ingresos Brutos")]
        public string Ingresos_brutos { get; set; }

        [Required]
        [Display(Name = "Fecha Inicio - dd/mm/aaaa")]
        [ValidarFecha]
        public string fecha_inicios { get; set; }

        [Required]
        [StringLength(maximumLength: 11, ErrorMessage = "El CUIT debe tener como maximo {0} caracteres ")]
        [Display(Name = "CUIT")]
        public string CUIT { get; set; }
    }

    public class EditarComercioViewModel
    {
        public int id { get; set; }

        [Required]
        [StringLength(maximumLength: 50, ErrorMessage = "La razon social debe tener como maximo {0} caracteres ")]
        [Display(Name = "Razon Social")]
        public string razon_social { get; set; }

        [Required]
        [Display(Name = "Situación frente al IVA")]
        public int id_IVA { get; set; }
        public string descripcion { get; set; }

        [Required]
        [StringLength(maximumLength: 16, ErrorMessage = "Ingresos Brutos debe tener como maximo {0} caracteres ")]
        [Display(Name = "Ingresos Brutos")]
        public string Ingresos_brutos { get; set; }

        [Required]
        [Display(Name = "Fecha Inicio - dd/mm/aaaa")]
        [ValidarFecha]
        public string fecha_inicios { get; set; }
        public DateTime fecha_inicio { get; set; }

        [Required]
        [StringLength(maximumLength: 11, ErrorMessage = "El CUIT debe tener como maximo {0} caracteres ")]
        [Display(Name = "CUIT")]
        public string CUIT { get; set; }
    }

        public class ValidarFecha : ValidationAttribute
        {
            protected override ValidationResult IsValid(object value, ValidationContext validationContext)
            {
                string fecha = (string)value;
                DateTime fechavalidada;
                if (fecha.Length != 10)
                    return new ValidationResult("El formato debe ser dd/mm/aaaa");
            
                if (! Int32.TryParse(fecha.Substring(0, 2), out int dia) )
                    return new ValidationResult("El formato debe ser dd/mm/aaaa");
                if (!Int32.TryParse(fecha.Substring(3, 2), out int mes))
                    return new ValidationResult("El formato debe ser dd/mm/aaaa");
                if (!Int32.TryParse(fecha.Substring(6, 4), out int anio))
                    return new ValidationResult("El formato debe ser dd/mm/aaaa");
                if (fecha.Substring(2,1) != "/" && fecha.Substring(5, 1) != "/")
                    return new ValidationResult("El formato debe ser dd/mm/aaaa");
                if (!DateTime.TryParse(fecha, out fechavalidada))
                {
                    return new ValidationResult("Fecha invalida");
                }

                DateTime fechahoy = DateTime.Now;
                if (fechahoy < fechavalidada)
                {
                    return new ValidationResult("La fecha no puede ser mayor al dia de hoy");
                }


                return ValidationResult.Success;

            }
        }
}

proyecto-1/Models/comercio.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comercio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comercio()
        {
            this.empleado = new HashSet<empleado>();
        }
    
        public int id_comercio { get; set; }
        public string razon_social { get; set; }
        public string ingresos_brutos { get; set; }
        public Nullable<System.DateTime> fecha_inicio { get; set; }
        public string CUIT { get; set; }
        public string estado { get; set; }
        public Nullable<int> IVA { get; set; }
    
        public virtual situacion_iva situacion_iva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleado { get; set; }
    }
}

proyecto-1/Controllers/ComerciosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using proyecto_1.Models;
using proyecto_1.Models.ViewModel;

namespace proyecto_1.Controllers
{
    public class ComerciosController : Controller
    {
        // GET: Comercios
        public ActionResult Index()
        {
            int idComercio = 0;
            if (Session.Count > 1)
            {
                idComercio = (int)Session["comercio"];
            }
            List<ListaComerciosViewModel> lst = null;
            using (practicaprofesionalEntities1 db = new practicaprofesionalEntities1())
            {
                lst = (from c in db.comercio
                       where c.id_comercio != 0 && c.estado == "1"
                       select new ListaComerciosViewModel
                       {
                           id_comercio = c.id_comercio,
                           razon_social = c.razon_social,
                           ingresos_brutos = c.ingresos_brutos,
                           fecha_inicio = (DateTime)c.fecha_inicio, 
                           CUIT = c.CUIT,
                           IVA = (int) c.IVA
                       }).ToList();
            }
            return View(lst);
        }


        [HttpGet]
        public ActionResult Crear()
        {
            //Select de situacion frente al IVA
            List<ComercioViewModel> lst = null;
            using (Models.practicaprofesionalEntities1 db = new Models.practicaprofesionalEntities1())
            {
                lst = (from d in db.situacion_iva
                       select new ComercioViewModel
                       {
                           id_IVA = d.id_iva,
                           descripcion = d.descripcion
                       }).ToList();
            }

            List<SelectListItem> items = lst.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.descripcion.ToString(),
                    Value = d.id_IVA.ToString(),
                    Selected = false

                };
            });
            ViewBag.items = items;

            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Crear(ComercioViewModel model)
        {

            int idComercio = (int)Session["comercio"];

            if (!ModelState.IsValid)
            {
                //Select de situacion frente al IVA
                List<ComercioViewModel> lst = null;
                using (Models.practicaprofesionalEntities1 db = new Models.practicaprofesionalEntities1())
                {
                    lst = (from d in db.situacion_iva
                           select new ComercioViewModel
                           {
                               id_IVA = d.id_iva,
                               descripcion = d.descripcion
                           }).ToList();
                }

                List<SelectListItem> items = lst.ConvertAll(d =>
                {
                    return new SelectListItem()
                    {
                        Text = d.descripcion.ToString(),
                        Value = d.id_IVA.ToString(),
                        Selected = false

                    };
                });
                ViewBag.items = items;
                return View(model);
            }

            using (practicaprofesionalEntities1 db = new practicaprofesionalEntities1())
            {
                comercio oComercio = new comercio();

                oComercio.razon_social = model.razon_social;
                oComercio.estado = "1";
                oComercio.IVA = model.id_IVA;
                oComercio.ingresos_brutos = model.Ingresos_brutos;
                oComercio.CUIT = model.CUIT;
                oComercio.fecha_inicio = Convert.ToDateTime(model.fecha_inicios);
                //oComercio.fecha_inicio = model.fecha_inicio;

                db.comercio.Add(oComercio);

                db.SaveChanges();
                TempData["Referrer"] = "SaveRegister";
            }

            return Redirect(Url.Content("~/Comercios"));
        }

        public ActionResult Editar(int id)
        {

            //Select de situacion frente al IVA
            List<ComercioViewModel> lst = null;
            using (Models.practicaprofesionalEntities1 db = new Models.practicaprofesionalEntities1())
            {
                lst = (from d in db.situacion_iva
                       select new ComercioViewModel
                       {
                           id_IVA = d.id_iva,
                           descripcion = d.descripcion
                       }).ToList();
            }

            List<SelectListItem> items = lst.ConvertAll(d =>
            {
                return new SelectListItem()
                {
                    Text = d.descripcion.ToString(),
                    Value = d.id_IVA.ToString(),
                    Selected = false

                };
            });
            ViewBag.items = items;

            EditarComercioViewModel model = new EditarComercioViewModel();

            using (var db = new practicaprofesionalEntities1())
            {
                var oComercio = db.comercio.Find(id);
                model.razon_social = oComercio.razon_social;
                model.id_IVA = (int) oComercio.IVA;
                model.Ingresos_brutos = oComercio.ingresos_brutos;
                model.fecha_inicio = (DateTime) oComercio.fecha_inicio;
                model.CUIT = oComercio.CUIT;

            }
            model.fecha_inicios = model.fecha_inicio.ToShortDateString();
            return View(model);

        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Editar(EditarComercioViewModel model)
        {
            if (!ModelState.IsValid)
            {  
                //Select de situacion frente al IVA
                List<ComercioViewModel> lst = null;
                using (Models.practicaprofesionalEntities1 db = new Models.practicaprofesionalEntities1())
                {
                    lst = (from d in db.situacion_iva
                           select new ComercioViewModel
                           {
                               id_IVA = d.id_iva,
                               descripcion = d.descripcion
                           }).ToList();
                }

                List<SelectListItem> items = lst.ConvertAll(d =>
                {
                    return new SelectListItem()
                    {
                        Text = d.descripcion.ToString(),
                        Value = d.id_IVA.ToString(),
                        Selected = false

                    };
                });
                ViewBag.items = items;
                return View(model);
            }

            using (var db = new practicaprofesionalEntities1())
            {
                var oComercio = db.comercio.Find(model.id);
                oComercio.razon_social = model.razon_social;
                oComercio.IVA = model.id_IVA;
                oComercio.ingresos_brutos = model.Ingresos_brutos;
                oComercio.fecha_inicio = Convert.ToDateTime(model.fecha_inicios);
                oComercio.CUIT = model.CUIT;


                db.Entry(oComercio).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                TempData["Referrer"] = "SaveRegister";

            }

            return Redirect(Url.Content("~/Comercios"));

        }

        [HttpPost]
        public ActionResult Eliminar(int id)
        {
            try
            {
                using (var db = new practicaprofesionalEntities1())
                {
                    var oComercio = db.comercio.Find(id);
                    oComercio.estado = "0"; //eliminado logico

                    db.Entry(oComercio).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }

                return Content("1");
            }
            catch (Exception e)
            {
                return Content("ocurrio un problema al elminar el producto", e.Message);
            }
        }
    }
}
    
    
    

proyecto-1/Views/Comercios/Crear.cshtml
@model proyecto_1.Models.ViewModel.ComercioViewModel
@{
    ViewBag.Title = "Crear";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-md-12">

        @using (Html.BeginForm("Crear", "Comercios", FormMethod.Post, new { role = "form", @class = "" }))
        {
            @Html.AntiForgeryToken() //arroja excepcion no controlada


            @Html.ValidationMessage("error", new { @class = "text-danger" })



            @Html.LabelFor(d => d.razon_social)
            <br />@Html.ValidationMessageFor(d => d.razon_social, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.razon_social, new { @class = "form-control" })


            @Html.LabelFor(d => d.id_IVA)
            @Html.DropDownListFor(d => d.id_IVA, items, new { @class = "form-control" });


            @Html.LabelFor(d => d.Ingresos_brutos)
            <br />@Html.ValidationMessageFor(d => d.Ingresos_brutos, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.Ingresos_brutos, new { @class = "form-control" })

            @Html.LabelFor(d => d.fecha_inicios)
            <br />@Html.ValidationMessageFor(d => d.fecha_inicios, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.fecha_inicios, new { @class = "form-control" })

            @Html.LabelFor(d => d.CUIT)
            <br />@Html.ValidationMessageFor(d => d.CUIT, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.CUIT, new { @class = "form-control" })



            <div style="text-align:center" class="boton">
                <input type="button" value="Volver" class="btn btn-primary" onclick="document.location.href= '@Url.Content("~/Comercios/Index")'" />
                <input type="submit" class="btn btn-primary" value="Crear" />

            </div>

        }
    </div>

</div>

proyecto-1/Views/Comercios/Editar.cshtml
@model proyecto_1.Models.ViewModel.EditarComercioViewModel
@{
    ViewBag.Title = "Editar";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
}

<h2>Editar</h2>

<div class="row">
    <div class="col-md-12">

        @using (Html.BeginForm("Editar", "Comercios", FormMethod.Post, new { role = "form", @class = "" }))
        {
            @Html.AntiForgeryToken() //arroja excepcion no controlada

            @Html.ValidationMessage("error", new { @class = "text-danger" })

            @Html.HiddenFor(d => d.id)


            @Html.LabelFor(d => d.razon_social)
            <br />@Html.ValidationMessageFor(d => d.razon_social, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.razon_social, new { @class = "form-control" })


            @Html.LabelFor(d => d.id_IVA)
            @Html.DropDownListFor(d => d.id_IVA, items, new { @class = "form-control" });


            @Html.LabelFor(d => d.Ingresos_brutos)
            <br />@Html.ValidationMessageFor(d => d.Ingresos_brutos, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.Ingresos_brutos, new { @class = "form-control" })

            @Html.LabelFor(d => d.fecha_inicios)
            <br />@Html.ValidationMessageFor(d => d.fecha_inicios, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.fecha_inicios, new { @class = "form-control" })

            @Html.LabelFor(d => d.CUIT)
            <br />@Html.ValidationMessageFor(d => d.CUIT, "", new { @class = "text-danger" })
            @Html.TextBoxFor(d => d.CUIT, new { @class = "form-control" })



            <div style="text-align:center" class="boton">
                <input type="button" value="Volver" class="btn btn-primary" onclick="document.location.href= '@Url.Content("~/Comercios/Index")'" />
                <input type="submit" class="btn btn-primary" value="Editar" />

            </div>

        }
    </div>

</div>

proyecto-1/Views/Comercios/Index.cshtml
@model List<proyecto_1.Models.ViewModel.ListaComerciosViewModel>
@{
    ViewBag.Title = "Comercios";
}

<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="boton">
        <input type="submit" value="Agregar" class="btn btn-primary" onclick="document.location.href= '@Url.Content("~/Comercios/Crear")'" />
    </div>
</div>

@if ((string)TempData["Referrer"] == "SaveRegister")
{
    <div class="alert alert-success">
        <strong>Su carga se realizo exitosamente</strong>
    </div>
}

<div class="row">
    <div class="col-lg-12">
        <table class="table" id="datatable">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Razon Social</th>
                    <th>CUIT</th>
                    <th>IVA</th>
                    <th>Ingresos Brutos</th>
                    <th>Fecha de inicio</th>
                    <th> </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var oComercio in Model)
                {
                    <tr>
                        <td>@oComercio.id_comercio </td>
                        <td>@oComercio.razon_social </td>
                        <td>@oComercio.CUIT </td>
                        <td>@oComercio.IVA </td>
                        <td>@oComercio.ingresos_brutos </td>
                        <td>@oComercio.fecha_inicio.ToShortDateString()  </td>
                        <td>

                            <input type="submit" value="Editar" class="btn btn-success" onclick="document.location.href='@Url.Content("~/Comercios/Editar/"+ oComercio.id_comercio)'" />

                            <input type="submit" value="Eliminar" class="btn btn-danger" onclick="jsDelete(@oComercio.id_comercio);" />

                        </td>

                    </tr>
                }
            </tbody>
        </table>

    </div>

</div>

@section scripts{
    <script>
        $(document).ready(function () {
            $('#datatable').DataTable();
        });



    </script>
}

<script>
     function jsDelete(id) {
         if (confirm("esta seguro que desa confirmar?"))
         {
                url = "@Url.Content("~/Comercios/Eliminar")" + "/" + id;

            $.post(url, function (data)
            {
                if (data == "1")
                {
                      document.location.href = "@Url.Content("~/Comercios")"
                }
                else
                {
                        alert("ocurrio un problema al eliminar el Comercio")
                }
            })
         }
     }
</script>